-- Admin console: onboarding, offboarding and an audit trail.
-- Run after supabase-admin-management-migration.sql. Existing records are preserved.
begin;

-- ---------- 1) Employment status ----------
-- Offboarding keeps the person and all their history; it only stops them
-- logging in and takes them out of the live schedule. Deleting an employee
-- (which cascades their attendance and results away) stays a separate action.
alter table public.profiles
  add column if not exists status      text not null default 'active',
  add column if not exists exit_date   date,
  add column if not exists exit_reason text;

alter table public.profiles drop constraint if exists profiles_status_ck;
alter table public.profiles add constraint profiles_status_ck
  check (status in ('active', 'inactive'));

create index if not exists profiles_status_idx on public.profiles (status);

-- ---------- 2) Admin audit trail ----------
-- Who did what in the admin console. Written by the server with the service
-- key on every non-read action, so a change can always be traced back.
-- Never stores passwords, OTP codes, message bodies or webhook secrets.
create table if not exists public.admin_audit (
  id           bigint generated by default as identity primary key,
  created_at   timestamptz not null default now(),
  action       text not null,
  -- The employee or record the action was aimed at, denormalised so the log
  -- still reads correctly after that row is edited or deleted.
  target_id    text,
  target_label text,
  summary      text,
  status       text not null default 'ok' check (status in ('ok', 'failed')),
  http_status  int,
  detail       text,
  actor_ip     text
);

create index if not exists admin_audit_created_idx on public.admin_audit (created_at desc);
create index if not exists admin_audit_action_idx  on public.admin_audit (action, created_at desc);
create index if not exists admin_audit_target_idx  on public.admin_audit (target_id, created_at desc);

alter table public.admin_audit enable row level security;
revoke all on public.admin_audit from anon, authenticated;
grant all on public.admin_audit to service_role;
grant usage, select on sequence public.admin_audit_id_seq to service_role;

commit;
