-- Web Push subscriptions — one row per browser/device a user enabled
-- notifications on. RLS enabled with NO policies: only the service role
-- (via /api/push) can read or write these rows.

create table if not exists public.push_subscriptions (
  id         bigint generated by default as identity primary key,
  user_id    uuid not null references auth.users(id) on delete cascade,
  endpoint   text not null unique,
  p256dh     text not null,
  auth       text not null,
  user_agent text,
  created_at timestamptz not null default now()
);

alter table public.push_subscriptions enable row level security;

create index if not exists push_subscriptions_user_idx
  on public.push_subscriptions (user_id);
