-- Run in Supabase SQL Editor before using the extended employee editor.
-- Existing employment and attendance records are preserved.
begin;
alter table public.profiles
  add column if not exists department text,
  add column if not exists job_title text,
  add column if not exists phone text,
  add column if not exists joining_date date,
  add column if not exists manager_id uuid references public.profiles(id) on delete set null;
create index if not exists profiles_manager_idx on public.profiles(manager_id);
-- Outgoing SMTP attempts. No message bodies, subjects, passwords, or OTPs.
create table if not exists public.mail_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  company text, recipient text, category text not null default 'system',
  status text not null check(status in ('accepted','failed')),
  sender text, message_id text, reason text
);
create index if not exists mail_events_created_idx on public.mail_events(created_at desc);
alter table public.mail_events enable row level security;
revoke all on public.mail_events from anon, authenticated;
grant all on public.mail_events to service_role;
grant usage, select on sequence public.mail_events_id_seq to service_role;
commit;
